from app import db, Sections, Courses, Departments, Numbers, Professors, Meetings

db.drop_all()
db.create_all()

# Departments
ACP = Departments(code='ACP', name='Academic & Career Planning')
AMS = Departments(code='AMS', name='American Studies')
ANT = Departments(code='ANT', name='Anthropology')
ART = Departments(code='ART', name='Art and Design')
BCM = Departments(code='BCM', name='Biochemistry')
BIO = Departments(code='BIO', name='Biology')
BUS = Departments(code='BUS', name='Business Administration')
CHM = Departments(code='CHM', name='Chemistry')
CHN = Departments(code='CHN', name='Chinese')
COM = Departments(code='COM', name='Communication')
CSC = Departments(code='CSC', name='Computer Science')
DAN = Departments(code='DAN', name='Dance')
DAT = Departments(code='DAT', name='Data Analytics')
ECN = Departments(code='ECN', name='Economics')
EDC = Departments(code='EDC', name='Education')
EGR = Departments(code='EGR', name='Engineering Science')
EHS = Departments(code='EHS', name='Exercise and Health Science')
ENG = Departments(code='ENG', name='English')
ENV = Departments(code='ENV', name='Environmental Studies')
FRN = Departments(code='FRN', name='French')
FYS = Departments(code='FYS', name='First Year Seminar')
GEO = Departments(code='GEO', name='Geology')
GRM = Departments(code='GRM', name='German')
HCA = Departments(code='HCA', name='Healthcare Administration')
HNR = Departments(code='HNR', name='Honors')
HST = Departments(code='HST', name='History')
HUM = Departments(code='HUM', name='Humanities')
IPH = Departments(code='IPH', name='Integrative Physiology & Health Science')
ISC = Departments(code='ISC', name='Integrated Science')
LIB = Departments(code='LIB', name='Library Science')
MTH = Departments(code='MTH', name='Mathematics')
MUS = Departments(code='MUS', name='Music')
NMS = Departments(code='NMS', name='New Media Studies')
NUR = Departments(code='NUR', name='Nursing')
PHL = Departments(code='PHL', name='Philosophy')
PHY = Departments(code='PHY', name='Physics')
POL = Departments(code='POL', name='Political Science')
PSY = Departments(code='PSY', name='Psychology')
REL = Departments(code='REL', name='Religious Studies')
SOC = Departments(code='SOC', name='Sociology')
SPN = Departments(code='SPN', name='Spanish')
THE = Departments(code='THE', name='Theatre')
WGS = Departments(code='WGS', name='Women"s & Gender Studies')

db.session.add_all(
    [ACP, AMS, ANT, ART, BCM, BIO, BUS, CHM, CHN, COM, CSC, DAN, DAT, ECN, EDC, EGR, EHS, ENG, ENV, FRN, FYS, GEO, GRM,
     HCA, HNR, HST, HUM, IPH, ISC, LIB, MTH, MUS, NMS, NUR, PHL, PHY, POL, PSY, REL, SOC, SPN, THE, WGS])
db.session.commit()

# Numbers
number1 = Numbers(number=1)
number2 = Numbers(number=2)
number3 = Numbers(number=3)
number4 = Numbers(number=4)
number5 = Numbers(number=5)
number6 = Numbers(number=6)
number7 = Numbers(number=7)
number8 = Numbers(number=8)
number9 = Numbers(number=9)
number10 = Numbers(number=10)
number11 = Numbers(number=11)
number12 = Numbers(number=12)
number13 = Numbers(number=13)
number14 = Numbers(number=14)
number15 = Numbers(number=15)
number16 = Numbers(number=16)
number17 = Numbers(number=17)
number18 = Numbers(number=18)
number19 = Numbers(number=19)
number20 = Numbers(number=20)
number21 = Numbers(number=21)

db.session.add_all(
    [number1, number2, number3, number4, number5, number6, number7, number8, number9, number10, number11, number12,
     number13, number14, number15, number16, number17, number19, number19, number20, number21])
db.session.commit()

# Professors
strobel = Professors(full_name='Strobel, Elizabeth A')
abernathy = Professors(full_name='Abernathy, Marc J')
abo = Professors(full_name='Abo, Takeshi')
andre = Professors(full_name='Andre, Phillip H')
argueta = Professors(full_name='Argueta-Diaz, Victor')
armstrong = Professors(full_name='Armstrong, Kathryn M')
ayres = Professors(full_name='Ayres, Jeffrey B')
babcock = Professors(full_name='Babcock, Melodee M')
bacon = Professors(full_name='Bacon, Leeza Lyn')
bailey = Professors(full_name='Bailey, Tricia M')
ball = Professors(full_name='Ball, Karen L')
barrett = Professors(full_name='Barrett, Brent Baxter')
beatty = Professors(full_name='Beatty, Amy E')
blazek = Professors(full_name='Blazek, Janelle L')
borrello = Professors(full_name='Borrello, Murray C')
bosley = Professors(full_name='Bosley-Smith, Emma Ryan')
bu = Professors(full_name='Bu, Liping')
burns = Professors(full_name='Bu, Liping')
calhoun = Professors(full_name='Calhoun, Eric S')
camenares = Professors(full_name='Camenares, Devin J')
cameron = Professors(full_name='Cameron, Elizabeth A')
campbell = Professors(full_name='Campbell, Dion Jamaal')
carman = Professors(full_name='Carman, Karen Ann')
cartrite = Professors(full_name='Cartrite, Britt A')
cartritek = Professors(full_name='Cartrite, Karla Jean')
chaplen = Professors(full_name='Chaplen, Ruth A')
chen = Professors(full_name='Chen, Chih-Ping')
cicci = Professors(full_name='Cicci, Matthew A')
clark = Professors(full_name='Clark, David L')
collamati = Professors(full_name='Collamati, Anthony J')
cook = Professors(full_name='Cook, Marissa L')
crain = Professors(full_name='Crain, Jason L')
cuccolo = Professors(full_name='Cuccolo, Kelly M')
cunningham = Professors(full_name='Cunningham, Robert P')
dai = Professors(full_name='Dai, Zhewei')
davis = Professors(full_name='Davis, Alissa C')
dexter = Professors(full_name='Dexter, Scott D')
dickson = Professors(full_name='Dickson, Jillian D')
diels = Professors(full_name='Diels, Janie A')
dixon = Professors(full_name='Dixon, Nicholas J')
dixons = Professors(full_name='Dixon, Sheryle D')
dopke = Professors(full_name='Dopke, Joel A')
dopke = Professors(full_name='Dopke, Nancy C')
doralaskey = Professors(full_name='Dora-Laskey, Prathim M')
doran = Professors(full_name='Doran, Michael')
dougherty = Professors(full_name='Dougherty, Deborah A')
doyle = Professors(full_name='Doyle, Brian J')
duncan = Professors(full_name='Duncan, Andrew J')
elalamicanning = Professors(full_name='El Alami Canning, Khanssaa')
ettinger = Professors(full_name='Ettinger, Ryan S')
fedewa = Professors(full_name='Fedewa, Edward W')
fiste = Professors(full_name='Fiste, James A')
fitzpatrick = Professors(full_name='Fitzpatrick, Michael L')
fonley = Professors(full_name='Fonley, Morgan R')
frederick = Professors(full_name='Frederick, Becca L')
furlong = Professors(full_name='Furlong, Patrick J')
gage = Professors(full_name='Gage, Jacquelyn R')
glenn = Professors(full_name='Glenn, Jonathan B')
gorton = Professors(full_name='Gorton, William A')
griffin = Professors(full_name='Griffin, Dennis')
gross = Professors(full_name='Gross, Murray G')
guiett = Professors(full_name='Guiett, Georgia E')
hancock = Professors(full_name='Hancock, James B')
harfmann = Professors(full_name='Harfmann, Brianna D')
harr = Professors(full_name='Harr, Quinn Patrick')
harrison = Professors(full_name='Harrison, Lynzee L')
harwood = Professors(full_name='Harwood, Amanda D')
haupt = Professors(full_name='Haupt, James F')
hinkel = Professors(full_name='Hinkel, Matthew P')
hull = Professors(full_name='Hull, Brett E')
hulme = Professors(full_name='Hulme, Derick L')
hurd = Professors(full_name='Hurd, Alisyn E')
jachimiak = Professors(full_name='Jachimiak, Terry D')
jensen = Professors(full_name='Jensen, Steuard B')
jerry = Professors(full_name='Jerry, Haley A')
johnson = Professors(full_name='Johnson, Ashley A')
kaylor = Professors(full_name='Kaylor, Lisa M')
keeton = Professors(full_name='Keeton, Timothy P')
kim = Professors(full_name='Kim, Hyun')
kimhj = Professors(full_name='Kim, Hyunjung')
kingsland = Professors(full_name='Kingsland, Kevin M')
klumpp = Professors(full_name='Klumpp, Karen S')
kozack = Professors(full_name='Kozack, Caitlin V')
krause = Professors(full_name='Krause, Aaron L')
lema = Professors(full_name='Lema, Evangelia')
lim = Professors(full_name='Lim, Hyunji')
lincoln = Professors(full_name='Lincoln, Adam M')
liu = Professors(full_name='Liu, Holly H')
luckett = Professors(full_name='Luckett, Brittany S')
mackenzie = Professors(full_name='Mackenzie, Scott A')
macmaster = Professors(full_name='MacMaster, Catherine C')
marable = Professors(full_name='Marable, Kenneth Leon')
masley = Professors(full_name='Masley, Kelly J')
mazzuca = Professors(full_name='Mazzuca, James W')
mccune = Professors(full_name='McCune, Renee L')
miller = Professors(full_name='Miller, Michelle')
millert = Professors(full_name='Miller, Tess A')
molina = Professors(full_name='Molina, Robert R')
montoye = Professors(full_name='Montoye, Alexander H')
munderloh = Professors(full_name='Munderloh, Aaron A')
munisteri = Professors(full_name='Munisteri, Benedict W')
murad = Professors(full_name='Murad, Allison E')
neyer = Professors(full_name='Neyer, Allison H')
nguyen = Professors(full_name='Nguyen, Thanh C')
nichols = Professors(full_name='Nichols, William W')
olbertson = Professors(full_name='Olbertson, Kristin A')
orzolek = Professors(full_name='Orzolek, Mariah V')
overla = Professors(full_name='Overla, Kendra Lee')
park = Professors(full_name='Park, Sangchul')
paul = Professors(full_name='Paul, Kathleen A')
peterson = Professors(full_name='Peterson, Benjamin L')
pomerville = Professors(full_name='Pomerville, Andrew D')
porter = Professors(full_name='Porter, Anne E')
radtke = Professors(full_name='Radtke, Joseph S')
richter = Professors(full_name='Richter, Marcus J')
riepma = Professors(full_name='Riepma, Zachary M')
roe = Professors(full_name='Roe, Michelle K')
rosen = Professors(full_name='Rosen, Monica L')
rossman = Professors(full_name='Rossman, Danielle L')
rowe = Professors(full_name='Rowe, John W')
russell = Professors(full_name='Russell, Eric M')
ryder = Professors(full_name='Ryder, Alicia V')
sabourin = Professors(full_name='Sabourin, Michelle M')
sawyer = Professors(full_name='Sawyer, Jacob S')
schiffman = Professors(full_name='Schiffman, Randy')
schippers = Professors(full_name='Schippers, James H')
sellers = Professors(full_name='Sellers, Andrew C')
selmon = Professors(full_name='Selmon, Michael L')
setterlund = Professors(full_name='Setterlund, Marc B')
sipka = Professors(full_name='Sipka, Timothy A')
slaughter = Professors(full_name='Slaughter, Stephany L')
smith = Professors(full_name='Smith, Matthew John')
sommerville = Professors(full_name='Sommerville, Jeffrey P')
spinner = Professors(full_name='Spinner, Elisabeth R')
store = Professors(full_name='Store, Jessie C')
stormont = Professors(full_name='Stormont, Samantha L')
strobel = Professors(full_name='Strobel, Elizabeth A')
stumpp = Professors(full_name='Stumpp, Edward')
swalve = Professors(full_name='Swalve, Natashia L')
szilagyi = Professors(full_name='Szilagyi, Christina E')
terhune = Professors(full_name='Terhune, Julia E')
thall = Professors(full_name='Thall, Andrew L')
thelen = Professors(full_name='Thelen, Peggy A')
turk = Professors(full_name='Turk, Jeffrey A')
vanderkooi = Professors(full_name='Vander Kooi, Lee J')
vivian = Professors(full_name='Vivian, Robert D')
vonwallmenich = Professors(full_name='von Wallmenich, Laura E K')
vranish = Professors(full_name='Vranish, Jennifer R')
walker = Professors(full_name='Walker, Victoria K')
wasserman = Professors(full_name='Wasserman, Daniel I')
westgate = Professors(full_name='Westgate, Bradford S')
westmoreland = Professors(full_name='Westmoreland, Randall S')
woolbright = Professors(full_name='Woolbright, Evan H')
woolbrightl = Professors(full_name='Woolbright, Lauren E')
worful = Professors(full_name='Worful, Andrea M')
wracan = Professors(full_name='Wracan, Nicholas W')
yandl = Professors(full_name='Yandl, David J')
yates = Professors(full_name='Yates, Peggy A')
young = Professors(full_name='Young, Tyler R')
zablocki = Professors(full_name='Zablocki, Alex M')
zablockiv = Professors(full_name='Zablocki, Victoria')
zerbe = Professors(full_name='Zerbe, David M')

db.session.add_all(
    [abernathy, abo, andre, argueta, armstrong, ayres, babcock, bacon, bailey, ball, barrett, beatty, blazek,
     borrello, bosley, bu, burns, calhoun, camenares, cameron, campbell, carman, cartrite, cartrite, chaplen, chen,
     cicci, clark, collamati, cook, crain, cuccolo, cunningham, dai, davis, dexter, dickson, diels, dixon, dixons,
     dopke, dopke, doralaskey, doran, dougherty, doyle, duncan, elalamicanning, ettinger, fedewa, fiste,
     fitzpatrick, fonley, frederick, furlong, gage, glenn, gorton, griffin, gross, guiett, hancock, harfmann, harr,
     harrison, harwood, haupt, hinkel, hull, hulme, hurd, jachimiak, jensen, jerry, johnson, kaylor, keeton, kim,
     kimhj, kingsland, klumpp, kozack, krause, lema, lim, lincoln, liu, luckett, mackenzie, macmaster, marable,
     masley, mazzuca, mccune, miller, millert, molina, montoye, munderloh, munisteri, murad, neyer, nguyen, nichols,
     olbertson, orzolek, overla, park, paul, peterson, pomerville, porter, radtke, richter, riepma, roe, rosen,
     rossman, rowe, russell, ryder, sabourin, sawyer, schiffman, schippers, sellers, selmon, setterlund, sipka,
     slaughter, smith, sommerville, spinner, store, stormont, strobel, stumpp, swalve, szilagyi, terhune, thall,
     thelen, turk, vanderkooi, vivian, vonwallmenich, vranish, walker, wasserman, westgate, westmoreland,
     woolbright, woolbrightl, worful, wracan, yandl, yates, young, zablocki, zablockiv, zerbe])

db.session.commit()

# Meeting times
time1 = Meetings(days='F', start='1:10:00', end='14:10:00')
time2 = Meetings(days='F', start='1:10:00', end='14:40:00')
time3 = Meetings(days='F', start='12:30:00', end='13:30:00')
time4 = Meetings(days='F', start='16:00:00', end='17:00:00')
time5 = Meetings(days='F', start='8:30:00', end='9:30:00')
time6 = Meetings(days='M', start='13:10:00', end='14:40:00')
time7 = Meetings(days='M', start='13:10:00', end='16:10:00')
time8 = Meetings(days='M', start='13:10:00', end='16:20:00')
time9 = Meetings(days='M', start='13:10:00', end='16:20:00')
time10 = Meetings(days='M', start='10:50:00', end='12:20:00')
time11 = Meetings(days='M', start='12:00:00', end='13:00:00')
time12 = Meetings(days='M', start='14:50:00', end='15:50:00')
time13 = Meetings(days='M', start='14:50:00', end='16:20:00')
time14 = Meetings(days='M', start='16:30:00', end='17:30:00')
time15 = Meetings(days='M', start='19:00:00', end='22:10:00')
time16 = Meetings(days='M', start='19:00:00', end='20:30:00')
time17 = Meetings(days='M', start='7:30:00', end='10:40:00')
time18 = Meetings(days='M', start='7:30:00', end='9:00:00')
time19 = Meetings(days='M', start='8:00:00', end='9:30:00')
time20 = Meetings(days='M', start='9:10:00', end='10:40:00')
time21 = Meetings(days='M', start='19:30:00', end='22:00:00')
time22 = Meetings(days='M Tu Th F', start='19:00:00', end='21:00:00')
time23 = Meetings(days='M Tu W Th', start='17:00:00', end='18:15:00')
time24 = Meetings(days='M Tu W Th F', start='17:00:00', end='18:15:00')
time25 = Meetings(days='M W', start='13:10:00', end='14:40:00')
time26 = Meetings(days='M W', start='13:10:00', end='16:20:00')
time27 = Meetings(days='M W', start='14:50:00', end='15:50:00')
time28 = Meetings(days='M W', start='14:50:00', end='16:20:00')
time29 = Meetings(days='M W', start='14:50:00', end='16:20:00')
time30 = Meetings(days='M W', start='19:00:00', end='20:30:00')
time31 = Meetings(days='M W', start='8:00:00', end='9:30:00')
time32 = Meetings(days='M W', start='9:40:00', end='11:50:00')
time33 = Meetings(days='M W F', start='12:00:00', end='13:00:00')
time34 = Meetings(days='M W F', start='13:10:00', end='14:10:00')
time35 = Meetings(days='M W F', start='10:50:00', end='11:50:00')
time36 = Meetings(days='M W F', start='	12:00:00', end='13:00:00')
time37 = Meetings(days='M W F', start='14:50:00', end='15:50:00')
time38 = Meetings(days='M W F', start='8:30:00', end='9:30:00')
time39 = Meetings(days='M W F', start='9:40:00', end='10:40:00')
time40 = Meetings(days='Th', start='13:10:00', end='14:40:00')
time41 = Meetings(days='Th', start='13:10:00', end='15:20:00')
time42 = Meetings(days='Th', start='13:10:00', end='15:50:00')
time43 = Meetings(days='Th', start='13:10:00', end='16:20:00')
time44 = Meetings(days='Th', start='11:20:00', end='12:50:00')
time45 = Meetings(days='Th', start='14:50:00', end='16:20:00')
time46 = Meetings(days='Th', start='19:00:00', end='22:10:00')
time47 = Meetings(days='Th', start='19:00:00', end='21:00:00')
time48 = Meetings(days='Th', start='19:00:00', end='21:10:00')
time49 = Meetings(days='Th', start='8:00:00', end='10:40:00')
time50 = Meetings(days='Th', start='8:00:00', end='11:10:00')
time51 = Meetings(days='Th', start='8:00:00', end='9:30:00')
time52 = Meetings(days='Th', start='9:00:00', end='11:10:00')
time53 = Meetings(days='Tu', start='13:10:00', end='5:10:00')
time54 = Meetings(days='Tu', start='13:10:00', end='15:20:00')
time55 = Meetings(days='Tu', start='13:10:00', end='15:50:00')
time56 = Meetings(days='Tu', start='13:10:00', end='16:20:00')
time57 = Meetings(days='Tu', start='11:20:00', end='12:50:00')
time58 = Meetings(days='Tu', start='14:50:00', end='16:20:00')
time59 = Meetings(days='Tu', start='19:00:00', end='22:10:00')
time60 = Meetings(days='Tu', start='19:00:00', end='21:10:00')
time61 = Meetings(days='Tu', start='19:00:00', end='21:30:00')
time62 = Meetings(days='Tu', start='8:00:00', end='10:40:00')
time63 = Meetings(days='Tu', start='8:00:00', end='11:10:00')
time64 = Meetings(days='Tu', start='8:00:00', end='9:30:00')
time65 = Meetings(days='Tu', start='8:30:00', end='9:30:00')
time66 = Meetings(days='Tu', start='13:10:00', end='14:40:00')
time67 = Meetings(days='Tu Th', start='13:10:00', end='16:20:00')
time68 = Meetings(days='Tu Th', start='11:20:00', end='12:20:00')
time69 = Meetings(days='Tu Th', start='11:20:00', end='12:50:00')
time70 = Meetings(days='Tu Th', start='14:20:00', end='15:20:00')
time71 = Meetings(days='Tu Th', start='14:50:00', end='15:50:00')
time72 = Meetings(days='Tu Th', start='14:50:00', end='16:20:00')
time73 = Meetings(days='Tu Th', start='15:20:00', end='16:20:00')
time74 = Meetings(days='Tu Th', start='16:00:00', end='16:55:00')
time75 = Meetings(days='Tu Th', start='18:00:00', end='21:00:00')
time76 = Meetings(days='Tu Th', start='19:00:00', end='20:00:00')
time77 = Meetings(days='Tu Th', start='8:00:00', end='9:30:00')
time78 = Meetings(days='Tu Th', start='20:00:00', end='23:00:00')
time79 = Meetings(days='Tu Th', start='20:00:00', end='21:00:00')
time80 = Meetings(days='Tu Th', start='8:30:00', end='9:30:00')
time81 = Meetings(days='Tu Th', start='9:40:00', end='11:10:00')
time82 = Meetings(days='Tu Th', start='9:40:00', end='12:40:00')
time83 = Meetings(days='W', start='13:10:00', end='14:40:00')
time84 = Meetings(days='W', start='13:10:00', end='15:20:00')
time85 = Meetings(days='W', start='13:10:00', end='16:20:00')
time86 = Meetings(days='W', start='14:50:00', end='16:20:00')
time87 = Meetings(days='W', start='18:00:00', end='19:00:00')
time88 = Meetings(days='W', start='18:15:00', end='19:00:00')
time89 = Meetings(days='W', start='18:30:00', end='19:30:00')
time90 = Meetings(days='W', start='19:00:00', end='22:10:00')
time91 = Meetings(days='W', start='19:00:00', end='21:00:00')
time92 = Meetings(days='W', start='19:00:00', end='21:10:00')
time93 = Meetings(days='W', start='19:30:00', end='22:30:00')
time94 = Meetings(days='W F', start='8:00:00', end='9:00:00')
db.session.add_all([time1, time2, time3, time4, time5, time6, time7, time8, time9, time10, time11, time12, time13,
                    time14, time15, time16, time17, time18, time19, time20, time21, time22, time23, time24, time25,
                    time26, time27, time28, time29, time30, time31, time32, time33, time34, time35, time36, time37,
                    time38, time39, time40, time41, time42, time43, time44, time44, time45, time46, time47, time48,
                    time49, time50, time51, time52, time53, time54, time55, time56, time57, time58, time59, time60,
                    time61, time62, time63, time64, time65, time66, time67, time68, time69, time70, time71, time72,
                    time73, time74, time75, time76, time77, time78, time79, time80, time81, time82, time83, time84,
                    time85, time86, time87, time88, time89, time90, time91, time92, time93, time94])
db.session.commit()

# Courses
acp100 = Courses(course='100', title='Strategic Learning', department=ACP)
ams101 = Courses(course='101', title='American Studies', department=AMS)
ams120 = Courses(course='120', title='Superheroes & Identity', department=AMS)
ant385 = Courses(course='385', title='Museum Internship', department=ANT)
art101 = Courses(course='101', title='Drawing I', department=ART)
art111 = Courses(course='111', title='History of Art I', department=ART)
art120 = Courses(course='120', title='Two-Dimensional Design', department=ART)
art126 = Courses(course='126', title='Photography I', department=ART)
art140 = Courses(course='140', title='Ceramics I', department=ART)
art150 = Courses(course='150', title='3-Dimensional Design', department=ART)
art180 = Courses(course='180', title='Drawing Comics', department=ART)
art228 = Courses(course='228', title='Lighting Studio', department=ART)
art231 = Courses(course='231', title='Graphic Design II', department=ART)
art241 = Courses(course='241', title='Wheel Throwing', department=ART)
art361 = Courses(course='361', title='Drawing and Painting I', department=ART)
art461 = Courses(course='461', title='Drawing and Painting III', department=ART)
art500 = Courses(course='500', title='Poetry and Illustration', department=ART)
art501 = Courses(course='501', title='Professional Practice I', department=ART)
bcm280 = Courses(course='280', title='i-GEM Workshop', department=BCM)
bcm321 = Courses(course='321', title='Biochemistry', department=BCM)
bcm321l = Courses(course='321L', title='BCM 321 Laboratory', department=BCM)
bcm399 = Courses(course='399', title='Magnetotactic Bacteria', department=BCM)
bio121 = Courses(course='121', title='Foundations of Biology', department=BIO)
bio121l = Courses(course='121L', title='BIO 121 Laboratory', department=BIO)
bio223 = Courses(course='223', title='Animal Biology', department=BIO)
bio223l = Courses(course='223L', title='Bio 223 Laboratory', department=BIO)
bio299 = Courses(course='299', title='PCR of Pine River Sediment', department=BIO)
bio302 = Courses(course='302', title='Ecology', department=BIO)
bio302l = Courses(course='302L', title='BIO 302 Laboratory', department=BIO)
bio308 = Courses(course='308', title='Microbiology', department=BIO)
bio308l = Courses(course='308L', title='BIO 308 Laboratory', department=BIO)
bio309 = Courses(course='309', title='Aquatic Biology', department=BIO)
bio309l = Courses(course='309L', title='Aquatic Biology - Lab', department=BIO)
bio330 = Courses(course='330', title='Immunology', department=BIO)
bio361 = Courses(course='361', title='Animal Behavior', department=BIO)
bio361l = Courses(course='361L', title='Animal Behavior - Lab', department=BIO)
bio490 = Courses(course='490', title='Senior Capstone Seminar', department=BIO)
bio499 = Courses(course='499', title='Taste Receptor PCR Assay', department=BIO)
bus117 = Courses(course='117', title='Business Analytics I', department=BUS)
bus121 = Courses(course='121', title='Values Driven Organizations', department=BUS)
bus221 = Courses(course='221', title='Financial Accounting', department=BUS)
bus225 = Courses(course='225', title='Legal Environment of Business', department=BUS)
bus280 = Courses(course='280', title='Sports & Ent Spnshp & Sales', department=BUS)
bus309 = Courses(course='309', title='Managerial Finance', department=BUS)
bus321 = Courses(course='321', title='Intermediate Accounting I', department=BUS)
bus323 = Courses(course='323', title='Management', department=BUS)
bus331 = Courses(course='331', title='Cost Accounting', department=BUS)
bus333 = Courses(course='333', title='Marketing', department=BUS)
bus366 = Courses(course='366', title='Commercial Law', department=BUS)
bus380 = Courses(course='380', title='Risk Management', department=BUS)
bus385 = Courses(course='385', title='Disney College Program', department=BUS)
bus386 = Courses(course='386', title='Disney College Program II', department=BUS)
bus426 = Courses(course='426', title='Federal Business Taxation', department=BUS)
bus440 = Courses(course='440', title='Global Strategic Management', department=BUS)
bus449 = Courses(course='449', title='Auditing', department=BUS)

course1 = Courses(course='', title='', department=BUS)
db.session.add_all(
    [acp100, ams101, ams120, ant385, art101, art111, art120, art126, art140, art150, art180, art228, art231, art241,
     art361, art461, art500, bcm280, bcm321, bcm321l, bcm399, bio121, bio121l, bio223, bio223l, bio299, bio302, bio302l,
     bio308, bio308l, bio309, bio309l, bio330, bio361, bio361l, bio490, bio499, bus117, bus121, bus221, bus225, bus280,
     bus309, bus321, bus323, bus331, bus333, bus366, bus380, bus385, bus386, bus426, bus440, bus449
     ])

db.session.commit()

# section1 = Sections(courses=, numbers=number1, professors=, meetings=)
acp100_01 = Sections(courses=acp100, numbers=number1, professors=strobel, meetings=time44)
acp100_02 = Sections(courses=acp100, numbers=number1, professors=strobel, meetings=time44)
# ams101_01 = Sections(courses=ams101, numbers=number1, professors=woolbright, meetings=)
# ant385_01 = Sections(courses=ant385, numbers=number1, professors=diels, meetings=)
art101_01 = Sections(courses=art101, numbers=number1, professors=dickson, meetings=time67)
# art111_01 = Sections(courses=art111, numbers=number1, professors=cook, meetings=)
# art120_01 = Sections(courses=art120, numbers=number1, professors=vanderkooi, meetings=)
# art126_01 = Sections(courses=art126, numbers=number1, professors=harrison, meetings=)
# art140_01 = Sections(courses=art140, numbers=number1, professors=zablocki, meetings=)
# art150_01 = Sections(courses=art150, numbers=number1, professors=zablocki, meetings=)
# art180_01 = Sections(courses=art180 , numbers=number1, professors=dickson, meetings=)
# art228_01 = Sections(courses=art228 , numbers=number1, professors=harrison, meetings=)
# art231_01 = Sections(courses=art231, numbers=number1, professors=vanderkooi, meetings=)
# art241_01 = Sections(courses=art241, numbers=number1, professors=zablocki, meetings=)
# art241_02 = Sections(courses=art241, numbers=number2, professors=zablocki, meetings=)
# art361_01 = Sections(courses=art361, numbers=number1, professors=dickson, meetings=)
# art461_01 = Sections(courses=art461 , numbers=number1, professors=dickson, meetings=)
# art500_01 = Sections(courses=art500, numbers=number1, professors=dickson, meetings=)
# art501_01 = Sections(courses=art501, numbers=number1, professors=dickson, meetings=)
bcm280_01 = Sections(courses=bcm280, numbers=number1, professors=camenares, meetings=time69)
# bcm321_01 = Sections(courses=bcm321, numbers=number1, professors=camenares, meetings=)
# bcm321l_01 = Sections(courses=bcm321l , numbers=number1, professors=camenares, meetings=)
# bcm321l_02 = Sections(courses=bcm321l , numbers=number2, professors=camenares, meetings=)
# bcm321l_03 = Sections(courses=bcm321l , numbers=number3, professors=camenares, meetings=)
bcm321l_04 = Sections(courses=bcm321l, numbers=number4, professors=camenares, meetings=time43)
# bcm399_01 = Sections(courses=bcm399, numbers=number1, professors=camenares, meetings=)
# bio121_01 = Sections(courses=bio121, numbers=number1, professors=calhoun, meetings=)
# bio121_02 = Sections(courses=bio121, numbers=number2, professors=doyle, meetings=)
# bio121l_01 = Sections(courses=bio121l , numbers=number1, professors=doyle, meetings=)
# bio121l_02 = Sections(courses=bio121l , numbers=number2, professors=calhoun, meetings=)
# bio121l_03 = Sections(courses=bio121l , numbers=number3, professors=kingsland, meetings=)
bio121l_04 = Sections(courses=bio121l, numbers=number4, professors=keeton, meetings=time43)
# bio223_01 = Sections(courses=bio223 , numbers=number1, professors=clark, meetings=)
# bio223l_01 = Sections(courses=bio223l, numbers=number1, professors=clark, meetings=)
# bio223l_02 = Sections(courses=bio223l, numbers=number2, professors=clark, meetings=)
# bio299_01 = Sections(courses=bio299 , numbers=number1, professors=keeton, meetings=)
# bio299_02 = Sections(courses=bio299 , numbers=number2, professors=harwood, meetings=)
bio302_01 = Sections(courses=bio302, numbers=number1, professors=rowe, meetings=time69)
# bio302l_01 = Sections(courses=bio302l , numbers=number1, professors=, meetings=)
# bio308_01 = Sections(courses=bio308 , numbers=number1, professors=, meetings=)
# bio308l_01 = Sections(courses=bio308l, numbers=number1, professors=, meetings=)
# bio309_01 = Sections(courses=bio309 , numbers=number1, professors=, meetings=)
# bio309l_01 = Sections(courses=bio309l , numbers=number1, professors=, meetings=)
# bio330_01 = Sections(courses=bio330 , numbers=number1, professors=, meetings=)
# bio361_01 = Sections(courses=bio361 , numbers=number1, professors=, meetings=)
bio361l_01 = Sections(courses=bio361l, numbers=number1, professors=clark, meetings=time43)
# bio490_01 = Sections(courses=bio490 , numbers=number1, professors=, meetings=)
# bio499_01 = Sections(courses=bio499 , numbers=number1, professors=, meetings=)
# bus117_01 = Sections(courses=bus117, numbers=number1, professors=, meetings=)
# bus117_01 = Sections(courses=bus117, numbers=number1, professors=, meetings=)
# bus221_01 = Sections(courses=bus221 , numbers=number1, professors=, meetings=)
# bus225_01 = Sections(courses=bus225, numbers=number1, professors=, meetings=)
bus280_01 = Sections(courses=bus280, numbers=number1, professors=sellers, meetings=time69)
# bus309_01 = Sections(courses=bus309 , numbers=number1, professors=, meetings=)
# bus321_01 = Sections(courses=bus321 , numbers=number1, professors=, meetings=)
# bus323_01 = Sections(courses=bus323 , numbers=number1, professors=, meetings=)
bus331_01 = Sections(courses=bus331, numbers=number1, professors=haupt, meetings=time69)
# bus333_01 = Sections(courses=bus333 , numbers=number1, professors=, meetings=)
# bus366_01 = Sections(courses=bus366 , numbers=number1, professors=, meetings=)
# bus380_01 = Sections(courses=bus380 , numbers=number1, professors=, meetings=)
# bus385_01 = Sections(courses=bus385 , numbers=number1, professors=, meetings=)
# bus386_01 = Sections(courses=bus386, numbers=number1, professors=, meetings=)
# bus426_01 = Sections(courses=bus426 , numbers=number1, professors=, meetings=)
# bus440_01 = Sections(courses=bus440 , numbers=number1, professors=, meetings=)
# bus449_01 = Sections(courses=bus449, numbers=number1, professors=, meetings=)

db.session.add_all(
    [acp100_01, acp100_02, art101_01, bcm280_01, bcm321l_04, bio121l_04, bio302_01, bio361l_01, bus280_01, bus331_01])
db.session.commit()

print(acp100.id)
Sections.query.all()
Courses.query.all()
Departments.query.all()
Numbers.query.all()
Professors.query.all()
Meetings.query.all()
